const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.TEST_OUTPUT||path.join(root,'test-results'));fs.mkdirSync(out,{recursive:true});
const results=[],errors=[];let browser,context,page,empty,base,url;
const server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(fs.readFileSync(path.join(root,'hofmann-trace.html')));});
async function test(name,fn){const t=Date.now();try{await fn();results.push({name,passed:true,ms:Date.now()-t});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);await page.screenshot({path:path.join(out,'metaball-failure-'+results.length+'.png')});}}
const state=(p=page)=>p.evaluate(()=>JSON.parse(__hofmann.projectJson()));
const idle=(p=page)=>p.evaluate(()=>__hofmann.whenIdle());
async function load(data=base,p=page){assert.equal(await p.evaluate(d=>__hofmann.loadProject(JSON.stringify(d)),data),true);await idle(p);await p.locator('[data-tool=select]').click();}
async function change(v,p=page,finish=true){await p.locator('#filletIn').evaluate((el,{v,finish})=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));if(finish)el.dispatchEvent(new Event('change',{bubbles:true}));},{v,finish});await idle(p);}
async function tap(x,y,p=page){const q=await p.locator('#canvas').evaluate((svg,xy)=>{const q=new DOMPoint(...xy).matrixTransform(svg.getScreenCTM());return{x:q.x,y:q.y};},[x,y]);if(p===page)await p.mouse.click(q.x,q.y);else await p.touchscreen.tap(q.x,q.y);}
function capsule(a,b,id=1,flow='O'){return{id,closed:true,members:[a,b],holes:[],notches:[],soft:[],necks:[a<b?a+'|'+b:b+'|'+a],cuts:[],tangents:[{a,b,fA:flow,fB:flow},{a:b,b:a,fA:flow,fB:flow}]};}
async function vectorPixels(points){return page.evaluate(async points=>{const h=__hofmann;async function raster(text){const im=new Image();im.src='data:image/svg+xml,'+encodeURIComponent(text);await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.drawImage(im,0,0);return x;}
  const a=await raster(h.exportSvgString(false)),b=await raster(h.mergedSvgString(false)),p=a.getImageData(0,0,a.canvas.width,a.canvas.height).data,q=b.getImageData(0,0,b.canvas.width,b.canvas.height).data;let wrong=0;for(let i=3;i<p.length;i+=4)if((p[i]>250&&q[i]<5)||(p[i]<5&&q[i]>250))wrong++;return{wrong,alpha:points.map(xy=>a.getImageData(...xy,1,1).data[3]),finite:!/NaN|Infinity/.test(h.exportEpsString(false))};},points);}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'chrome',headless:true});context=await browser.newContext({viewport:{width:1280,height:900}});await context.route('https://fonts.**',r=>r.abort());page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.evaluate(()=>__hofmann.storageReady);empty=await state();base=structuredClone(empty);base.contours=[capsule('1_1','1_2')];base.nextId=2;
 await test('Every slider step keeps a neck and softens its depth evenly without crossing its opposite edge',async()=>{
   await load();const samples=await page.evaluate(()=>{const h=__hofmann,old=h.state.fillet,values=[];for(let v=0;v<=60;v++){h.state.fillet=v/100;const sg=h.contourSegments(h.state.contours[0]),top=sg.segs[0];values.push({value:v,neckCount:sg.hits.filter(x=>x.neck).length,depth:top.c.y+top.r-(120-21.3),halfWidth:120-top.c.y-top.r,valid:h.validContour(h.state.contours[0])});}h.state.fillet=old;return values;});
   assert.ok(samples.every(s=>s.neckCount===2&&s.valid&&s.halfWidth>2&&s.depth>0));const step=(samples[0].depth-samples[60].depth)/60;assert.ok(step>.1);for(let i=1;i<samples.length;i++)assert.ok(Math.abs(samples[i-1].depth-samples[i].depth-step)<1e-7,JSON.stringify(samples[i]));
   fs.writeFileSync(path.join(out,'metaball-progression.json'),JSON.stringify(samples,null,2));
 });
 await test('Arcs remain tangent for unequal radii, diagonal links, reversed contours and rounded squares',async()=>{
   for(const setup of [{},{nodes:{'1_1':{pct:40},'1_2':{pct:90}}},{diagonal:true},{reverse:true},{bevel:.5}]){
     const data=structuredClone(base);Object.assign(data,setup);if(setup.diagonal)data.contours=[capsule('1_1','2_2')];if(setup.reverse)data.contours=[capsule('1_2','1_1',1,'A')];await load(data);
     const joins=await page.evaluate(()=>{const h=__hofmann,old=h.state.fillet,checks=[];for(let v=0;v<=60;v+=5){h.state.fillet=v/100;const sg=h.contourSegments(h.state.contours[0]);let from=sg.start;const dirs=[];function unit(x,y){const n=Math.hypot(x,y);return n<1e-7?null:{x:x/n,y:y/n};}
       sg.segs.forEach(g=>{let a,b;if(g.t==='L'){a=b=unit(g.to.x-from.x,g.to.y-from.y);}else{const sign=g.flow==='O'?1:-1;a=unit(-(from.y-g.c.y)*sign,(from.x-g.c.x)*sign);b=unit(-(g.to.y-g.c.y)*sign,(g.to.x-g.c.x)*sign);}if(a&&b)dirs.push({a,b});from=g.to;});checks.push({v,hits:sg.hits.filter(h=>h.neck).length,joins:dirs.map((p,i)=>{const q=dirs[(i+1)%dirs.length].a;return p.b.x*q.x+p.b.y*q.y;})});}h.state.fillet=old;return checks;});
     for(const check of joins){assert.equal(check.hits,2,JSON.stringify(setup));assert.ok(check.joins.every(x=>x>.99999),JSON.stringify({setup,check}));}
   }
 });
 await test('Slider edits retain metaball selection at zero and undo or reopen exactly',async()=>{
   await load();const before=await state();for(const v of [0,8,17,30,47,60])await change(v,page,false);await change(60);assert.equal((await state()).contours[0].necks.length,1);await page.locator('#undoBtn').click();await idle();assert.deepEqual(await state(),before);await page.locator('#redoBtn').click();await idle();assert.equal((await state()).fillet,.6);await change(0);const saved=await state();await load(saved);assert.deepEqual(await state(),saved);assert.equal(await page.locator('.tan-hit.necked').count(),2);
   const p=await page.locator('.tan-hit.necked').first().evaluate(el=>{const q=el.getPointAtLength(el.getTotalLength()/2);const a=new DOMPoint(q.x,q.y).matrixTransform(el.getScreenCTM());return{x:a.x,y:a.y};});await page.mouse.click(p.x,p.y);assert.equal((await state()).contours[0].necks.length,0);assert.equal(await page.locator('.tan-hit.necked').count(),0);
 });
 await test('Negative metaball regions stay empty across the range and vector exports agree',async()=>{
   await load(empty);await page.evaluate(()=>__hofmann.startRelax([{x:90,y:90},{x:390,y:90},{x:390,y:390},{x:90,y:390}],false));await idle();const data=await state();data.contours[0].cuts=[{...capsule('2_2','2_3',20,'A'),cut:true}];data.nextId=21;await load(data);for(const v of [0,10,20,30,40,50,60]){await change(v);const result=await vectorPixels([[180,180],[210,180],[240,180],[150,150]]);assert.deepEqual(result.alpha,[0,0,0,255]);assert.equal(result.wrong,0);assert.equal(result.finite,true);}
 });
 await test('Touching and overlapping circles remain finite, while distant and square-only links stay unavailable',async()=>{
   for(const pct of [100,133]){const data=structuredClone(base);data.nodes={'1_1':{pct},'1_2':{pct}};await load(data);for(const v of [0,15,30,45,60]){await change(v);const report=await vectorPixels([[120,120],[150,120],[180,120]]);assert.deepEqual(report.alpha,[255,255,255]);assert.equal(report.wrong,0);assert.equal(report.finite,true);assert.equal(await page.evaluate(()=>__hofmann.contourSegments(__hofmann.state.contours[0]).hits.filter(h=>h.neck).length),2);}}
   for(const variant of ['far','square','tiny']){const data=structuredClone(base);if(variant==='far')data.contours=[capsule('1_1','1_6')];if(variant==='square')data.bevel=0;if(variant==='tiny')data.defaultPct=0;await load(data);for(const v of [0,30,60]){await change(v);assert.equal(await page.locator('.tan-hit').count(),0);assert.ok(await page.evaluate(()=>!/NaN|Infinity/.test(__hofmann.exportSvgString(false))));}}
 });
 await test('A five-step visual comparison shows the continuous transition',async()=>{
   await load();const svgs=[];for(const value of [0,15,30,45,60]){await change(value);svgs.push(await page.evaluate(()=>__hofmann.exportSvgString(true)));}const p=await context.newPage();await p.setViewportSize({width:1100,height:210});await p.setContent('<style>body{margin:0;background:#fff;font:13px Arial;color:#111;display:flex}figure{margin:0;width:220px;text-align:center;padding-top:22px}svg{display:block;width:200px;height:140px;margin:0 auto}figcaption{padding:8px}</style>'+svgs.map((svg,i)=>'<figure>'+svg.replace(/<\?xml[^>]*>/,'').replace(/viewBox="[^"]*"/,'viewBox="90 85 120 70"')+'<figcaption>'+i*25+' %</figcaption></figure>').join(''));await p.screenshot({path:path.join(out,'metaball-range.png')});await p.close();
 });
 await test('Mobile can activate or remove metaball at zero without opening the keyboard',async()=>{
   const ctx=await browser.newContext({viewport:{width:393,height:851},isMobile:true,hasTouch:true}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));try{await p.goto(url);const data=structuredClone(base);data.fillet=0;data.contours[0].necks=[];await load(data,p);const height=await p.locator('#canvas').evaluate(el=>el.getBoundingClientRect().height);await tap(150,120,p);await tap(150,98.7,p);assert.equal((await state(p)).contours[0].necks.length,1);assert.equal(await p.locator('.tan-hit.necked').count(),2);await p.locator('#tangentAction').tap();assert.equal((await state(p)).contours[0].necks.length,0);assert.notEqual(await p.evaluate(()=>document.activeElement.type),'number');assert.equal(await p.locator('#canvas').evaluate(el=>el.getBoundingClientRect().height),height);
     await p.locator('#aboutBtn').tap();assert.equal(await p.locator('.about li').last().innerText(),'Developed with Claude and Codex.');assert.equal(await p.locator('.ig').innerText(),'@eulst');assert.equal(await p.locator('.ig').evaluate(el=>el.nextSibling.textContent.trim()),'on Instagram.');await p.screenshot({path:path.join(out,'about-mobile.png')});}finally{await ctx.close();}
 });
 await test('Metaball survives geometry recalculation in the Worker and its fallback',async()=>{
   for(const fallback of [false,true]){const ctx=await browser.newContext();if(fallback)await ctx.addInitScript(()=>{window.Worker=undefined;});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));try{await p.goto(url);const data=structuredClone(base);data.fillet=0;await load(data,p);await p.evaluate(()=>__hofmann.selectNodes(['1_1']));const coords=await p.locator('#canvas').evaluate(svg=>[120,126].map(x=>{const q=new DOMPoint(x,120).matrixTransform(svg.getScreenCTM());return{x:q.x,y:q.y};}));await p.mouse.move(coords[0].x,coords[0].y);await p.mouse.down();await p.mouse.move(coords[1].x,coords[1].y,{steps:8});await p.mouse.up();await idle(p);assert.equal((await state(p)).contours[0].necks.length,1);assert.equal(await p.locator('.tan-hit.necked').count(),2);assert.ok(await p.evaluate(()=>__hofmann.state.contours.every(__hofmann.validContour)));}finally{await ctx.close();}}
 });
 await test('No runtime errors',async()=>assert.deepEqual(errors,[]));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'metaball-range.json'),JSON.stringify({results,errors},null,2));console.log(results.filter(r=>r.passed).length+'/'+results.length+' metaball-range scenarios passed');if(results.some(r=>!r.passed))process.exitCode=1;if(browser)await browser.close();server.close();});
