const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.TEST_OUTPUT||path.join(root,'test-results'));fs.mkdirSync(out,{recursive:true});
const results=[],errors=[];let browser,context,page,base,url;
const server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(fs.readFileSync(path.join(root,'hofmann-trace.html')));});
async function test(name,fn){if(process.env.TEST_FILTER&&!new RegExp(process.env.TEST_FILTER).test(name))return;const start=Date.now();try{await fn();results.push({name,passed:true,ms:Date.now()-start});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);await page.screenshot({path:path.join(out,'add-failure-'+results.length+'.png')});}}
const state=()=>page.evaluate(()=>JSON.parse(__hofmann.projectJson()));const idle=()=>page.evaluate(()=>__hofmann.whenIdle());const added=s=>Object.keys(s.nodes).filter(k=>k.startsWith('-1_')&&!s.nodes[k].disabled);
async function load(data=base){assert.equal(await page.evaluate(d=>__hofmann.loadProject(JSON.stringify(d)),data),true);await idle();await page.locator('[data-tool=select]').click();}
async function point(x,y,p=page){return p.locator('#canvas').evaluate((svg,{x,y})=>{const p=new DOMPoint(x,y).matrixTransform(svg.getScreenCTM());return{x:p.x,y:p.y};},{x,y});}
async function click(x,y){const p=await point(x,y);await page.mouse.click(p.x,p.y);}
async function add(x,y){if(await page.locator('#nodeAdd').getAttribute('aria-pressed')!=='true')await page.locator('#nodeAdd').click();await click(x,y);await idle();}
async function change(id,v){await page.locator('#'+id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));},v);await idle();}
async function remove(keys){await page.evaluate(keys=>__hofmann.selectNodes(keys),keys);await page.locator('#nodeDelete').click();await idle();}
async function undo(){await page.locator('#undoBtn').click();await idle();}
async function lasso(rect,sub=false){const [a,b,c,d]=rect;await page.evaluate(({points,sub})=>__hofmann.startRelax(points,sub),{points:[{x:a,y:b},{x:c,y:b},{x:c,y:d},{x:a,y:d}],sub});await idle();}
async function alpha(points){return page.evaluate(async points=>{const im=new Image();im.src='data:image/svg+xml,'+encodeURIComponent(__hofmann.exportSvgString(false));await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.drawImage(im,0,0);return points.map(p=>x.getImageData(...p,1,1).data[3]);},points);}
async function healthy(){const r=await page.evaluate(()=>{const h=__hofmann;return{valid:h.state.contours.every(h.validContour),error:h.engineInfo.lastError,nan:/NaN|Infinity/.test(h.exportSvgString(false))};});assert.equal(r.valid,true,JSON.stringify(r));assert.equal(r.nan,false);assert.ok(!r.error,r.error);}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'chrome',headless:true});context=await browser.newContext({viewport:{width:1280,height:900}});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.evaluate(()=>__hofmann.storageReady);base=await state();
 await test('Add replaces Size; Shift-click replaces Multiple without mutating the drawing',async()=>{
   await load();assert.equal(await page.locator('#nodeSize,#nodeMultiple').count(),0);assert.equal(await page.locator('#nodeAdd').isVisible(),true);const before=await state();await click(120,120);await page.keyboard.down('Shift');await click(180,120);await page.keyboard.up('Shift');assert.equal(await page.locator('#nodeCount').textContent(),'2 selected');assert.deepEqual(await state(),before);
 });
 await test('Add preview is non-destructive and places an independently editable support',async()=>{
   await load();const before=await state();await page.locator('#nodeAdd').click();const p=await point(150,150);await page.mouse.move(p.x,p.y);await page.waitForFunction(()=>!!document.querySelector('[data-add-preview]'));assert.deepEqual(await state(),before);await page.screenshot({path:path.join(out,'add-preview.png')});await page.mouse.click(p.x,p.y);await idle();const after=await state();assert.equal(added(after).length,1);assert.equal(after.version,3);const n=after.nodes['-1_1'];assert.ok(Math.abs(n.x-150)<.01&&Math.abs(n.y-150)<.01);assert.ok(n.pct>50&&n.pct<71);assert.equal(await page.locator('[data-node="-1_1"]').count(),1);assert.equal(await page.locator('#nodeAdd').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('#sizePop').evaluate(e=>e.classList.contains('open')),false);await healthy();
   assert.ok(await page.evaluate(()=>{const h=__hofmann;return h.activeKeys().filter(k=>k!=='-1_1').every(k=>h.gapNodes(h.nodeOf('-1_1'),h.nodeOf(k))>=1.99);}));await undo();assert.deepEqual(await state(),before);await page.locator('#redoBtn').click();await idle();assert.deepEqual(await state(),after);
 });
 await test('Occupied positions and cancelled placement do not create nodes or history entries',async()=>{
   await load();const before=await state();await add(180,180);assert.deepEqual(await state(),before);assert.match(await page.locator('#status').innerText(),/Not enough room/);assert.equal(await page.locator('#nodeAdd').getAttribute('aria-pressed'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('#nodeAdd').getAttribute('aria-pressed'),'false');assert.deepEqual(await state(),before);
   await page.locator('#nodeAdd').click();const p=await point(150,150);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.keyboard.press('Escape');await page.mouse.up();await idle();assert.deepEqual(await state(),before);
 });
 await test('Added supports can be filled, resized by double-click, moved and exported',async()=>{
   await load();await add(150,150);await page.locator('[data-tool=fill]').click();await click(150,150);assert.equal((await state()).nodes['-1_1'].filled,true);assert.equal((await alpha([[150,150]]))[0],255);await page.locator('[data-tool=select]').click();const p=await point(150,150);await page.mouse.dblclick(p.x,p.y);await change('szRange',20);await page.locator('#szOk').click();await idle();assert.equal((await state()).nodes['-1_1'].pct,20);
   const q=await point(160,155);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(q.x,q.y,{steps:8});await page.mouse.up();await idle();const n=(await state()).nodes['-1_1'];assert.ok(n.x>150&&n.y>150);assert.equal((await alpha([[160,155]]))[0],255);await healthy();await page.screenshot({path:path.join(out,'added-node.png')});
 });
 await test('Lasso includes added supports and negative lasso can remove them from a shape',async()=>{
   await load();await add(150,150);await lasso([128,128,172,172]);const s=await state();assert.equal(s.contours.length,1);assert.ok(s.contours[0].members.includes('-1_1'));assert.equal((await alpha([[150,150]]))[0],255);await healthy();await lasso([130,130,170,170],true);assert.equal((await alpha([[150,150]]))[0],0);await undo();assert.equal((await alpha([[150,150]]))[0],255);
 });
 await test('Adding an obstacle inside a shape makes a real hole; deleting it removes the hole',async()=>{
   await load();await lasso([90,90,270,270]);assert.equal((await alpha([[150,150]]))[0],255);await add(150,150);assert.equal((await alpha([[150,150]]))[0],0);await healthy();await remove(['-1_1']);assert.equal((await alpha([[150,150]]))[0],255);assert.equal(await page.locator('[data-node="-1_1"]').count(),0);await healthy();
 });
 await test('Added and grid nodes merge together and keep rounding, resize and free identity',async()=>{
   await load();await add(150,150);await page.evaluate(()=>__hofmann.selectNodes(['-1_1','1_1']));await page.locator('#nodeMerge').click();await idle();const n=(await state()).nodes['-1_1'];assert.equal(n.fused,true);assert.equal((await state()).nodes['1_1'].disabled,true);await change('bevelIn',0);assert.equal(await page.locator('[data-guide="-1_1"]').evaluate(el=>el.tagName),'rect');await healthy();
 });
 await test('Square and mirrored additions respect rounding and deduplicate points on mirror axes',async()=>{
   const data=structuredClone(base);data.bevel=0;data.sym='both';await load(data);await add(150,150);let s=await state();assert.equal(added(s).length,4);assert.equal(await page.locator('rect[data-guide^="-1_"]').count(),4);assert.ok(await page.evaluate(()=>{const h=__hofmann,keys=h.activeKeys();return keys.filter(k=>k.startsWith('-1_')).every(k=>keys.filter(q=>q!==k).every(q=>h.gapNodes(h.nodeOf(k),h.nodeOf(q))>=1.99));}));await undo();assert.equal(added(await state()).length,0);
   data.bevel=1;data.nodes={'2_3':{disabled:true},'4_3':{disabled:true}};await load(data);await add(240,180);s=await state();assert.equal(added(s).length,2);assert.ok(added(s).every(k=>s.nodes[k].x===240));
 });
 await test('Free nodes with ids beyond grid dimensions render and survive rotation and JSON roundtrip',async()=>{
   const data=structuredClone(base);data.version=3;data.nodes={'-1_20':{x:150,y:150,homeX:150,homeY:150,pct:40,filled:true}};await load(data);assert.equal((await alpha([[150,150]]))[0],255);await page.locator('#rotR').click();let s=await state();assert.equal(s.nodes['-1_20'].x,330);assert.equal(s.nodes['-1_20'].y,150);assert.equal((await alpha([[330,150]]))[0],255);await load(s);assert.deepEqual(await state(),s);await healthy();
 });
 await test('All 900 grid slots can stay active while adding a new circle',async()=>{
   const data=structuredClone(base);data.cols=data.rows=30;await load(data);await add(150,150);assert.equal(await page.locator('[data-node]').count(),901);assert.equal(await page.evaluate(()=>__hofmann.activeKeys().length),901);const s=await state();await load(s);assert.equal(await page.locator('[data-node]').count(),901);
 });
 await test('Removed free ids can be reused without restoring previous fill or shape membership',async()=>{
   await load();await add(150,150);await lasso([128,128,172,172]);await remove(['-1_1']);assert.equal((await state()).contours.length,0);await add(330,330);const s=await state();assert.equal(added(s).length,1);assert.equal(s.nodes['-1_1'].filled,false);assert.ok(Math.abs(s.nodes['-1_1'].x-330)<.01);assert.equal(s.contours.length,0);
 });
 await test('Invalid custom keys, missing positions and missing support definitions are rejected atomically',async()=>{
   await load();const before=await state();for(const [key,node] of [['-1_0',{x:150,y:150}],['-1_901',{x:150,y:150}],['-2_1',{x:150,y:150}],['-1_1',{x:150}],['-1_1',{x:-10,y:150}]]){const bad=structuredClone(base);bad.version=3;bad.nodes={[key]:node};assert.equal(await page.evaluate(d=>__hofmann.loadProject(JSON.stringify(d)),bad),false);}const bad=structuredClone(base);bad.version=3;bad.contours=[{id:1,single:'-1_1',members:['-1_1'],closed:true,tangents:[]}];assert.equal(await page.evaluate(d=>__hofmann.loadProject(JSON.stringify(d)),bad),false);assert.deepEqual(await state(),before);
 });
 await test('Autosave restores added supports with their edited size and artwork',async()=>{
   await load();await add(150,150);await lasso([128,128,172,172]);const before=await state();assert.equal(await page.evaluate(()=>__hofmann.saveSession()),true);await page.reload();await page.evaluate(()=>__hofmann.storageReady);await page.locator('#restoreSession').click();await idle();const restored=await state();for(const project of [before,restored])project.contours.forEach(c=>{c.cuts=c.cuts||[];c.necks=c.necks||[];});assert.deepEqual(restored,before);assert.equal((await alpha([[150,150]]))[0],255);
 });
 await test('Touch Add waits for release, cancels for pinch, and double-tap opens only the slider',async()=>{
   const ctx=await browser.newContext({viewport:{width:393,height:851},isMobile:true,hasTouch:true}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.evaluate(d=>__hofmann.loadProject(JSON.stringify(d)),base);await p.evaluate(()=>__hofmann.whenIdle());await p.locator('[data-tool=select]').tap();await p.locator('#nodeAdd').tap();const cdp=await ctx.newCDPSession(p),pos=await point(150,150,p);
   await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pos]});assert.equal(await p.evaluate(()=>__hofmann.activeKeys().length),49);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pos,{x:pos.x+55,y:pos.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[pos,{x:pos.x+95,y:pos.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await p.evaluate(()=>__hofmann.activeKeys().length),49);await p.locator('#zoomReset').tap();
   await p.touchscreen.tap(pos.x,pos.y);await p.evaluate(()=>__hofmann.whenIdle());assert.equal(await p.evaluate(()=>__hofmann.activeKeys().length),50);const height=await p.locator('#canvas').evaluate(el=>el.getBoundingClientRect().height);await p.touchscreen.tap(pos.x,pos.y);await p.touchscreen.tap(pos.x,pos.y);await p.locator('#sizePop.open').waitFor();assert.equal(await p.evaluate(()=>document.activeElement.type),'range');assert.equal(await p.locator('#canvas').evaluate(el=>el.getBoundingClientRect().height),height);await p.screenshot({path:path.join(out,'add-mobile.png')});await ctx.close();
 });
 await test('No runtime errors',async()=>assert.deepEqual(errors,[]));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'node-add.json'),JSON.stringify({results,errors},null,2));console.log(results.filter(r=>r.passed).length+'/'+results.length+' add-node scenarios passed');if(results.some(r=>!r.passed))process.exitCode=1;if(browser)await browser.close();server.close();});

